name: Notify Me

on:
  workflow_run:
    workflows: ["Update GitHub Repos JSON"]
    types: [completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram notification
        uses: Snr1s3/notify-telegram-action@v1.0.3
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          telegram_chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            ðŸ”” *${{ github.repository }}*
            *Workflow:* ${{ github.event.workflow_run.name }}
            *Conclusion:* ${{ github.event.workflow_run.conclusion }}
            *Run:* ${{ github.event.workflow_run.html_url }}
